In [2]:
import pandas as pd

# 读取数据
df = pd.read_csv('resources/sales.csv', usecols=['订单号', '产品类别', '产品名称', '销售数量', '单价'])
print(df)

# 数据处理
df['商品金额'] = df['销售数量'] * df['单价']
print(df)

# 写入数据
df.to_csv('resources/sales_01.csv', index=False)

            订单号  产品类别  产品名称  销售数量   单价
0    6805677496  家居用品    枕头    10  199
1    5857234132    食品    海苔     5   29
2    5888085059  电子产品  智能音箱     5  399
3    6823473137    食品    面包     3   29
4    6801664364    食品    薯片     2   19
..          ...   ...   ...   ...  ...
995  5887473055    图书    小说    10   49
996  5808511756    食品    坚果     2   79
997  5811169466    服装    围巾     4  129
998  6876456690    食品    果汁     7   39
999  6842608338    食品    蜂蜜     5   89

[1000 rows x 5 columns]
            订单号  产品类别  产品名称  销售数量   单价  商品金额
0    6805677496  家居用品    枕头    10  199  1990
1    5857234132    食品    海苔     5   29   145
2    5888085059  电子产品  智能音箱     5  399  1995
3    6823473137    食品    面包     3   29    87
4    6801664364    食品    薯片     2   19    38
..          ...   ...   ...   ...  ...   ...
995  5887473055    图书    小说    10   49   490
996  5808511756    食品    坚果     2   79   158
997  5811169466    服装    围巾     4  129   516
998  6876456690    食品    果汁     7   39   273
999  6842608338    食品    蜂蜜     5   89   445

[1000 rows x 6 columns]

In [8]:
df.head(10) # 显示前10行
df.tail(10) # 显示后10行
df.describe() # 显示统计数据
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
 5   商品金额    1000 non-null   int64
dtypes: int64(4), object(2)
memory usage: 47.0+ KB

In [13]:
df['产品名称']
df[['产品类别', '产品名称', '单价']]
df.iloc[0:5:1]

          订单号  产品类别  产品名称  销售数量   单价  商品金额
0  6805677496  家居用品    枕头    10  199  1990
1  5857234132    食品    海苔     5   29   145
2  5888085059  电子产品  智能音箱     5  399  1995
3  6823473137    食品    面包     3   29    87
4  6801664364    食品    薯片     2   19    38

In [17]:
df2 = pd.read_csv('resources/sales.csv')

# 配置项，展示所有的项目
pd.set_option('display.max_rows', None)

df[df['销售数量'] >= 10]  # 销售数量 >= 10
df[df['产品类别'].isin(['食品', '图书'])] # 产品类别为食品或图书
df[df['单价'].between(100, 200)] # 单价在100和200之间，包含边界
df[(df['销售数量'] >= 8) & (df['单价'] >= 100)] # 获取销售数量>=8并且单价>=100
df2[(df2['产品类别'].isin(['图书', '食品'])) & (df2['支付方式'].isin(['支付宝', '微信支付']))]

            订单号 产品类别   产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
4    6801664364   食品     薯片     2   19    NaN  微信支付  2025-06-02
9    5888085059   图书     字典     2   99     青岛  微信支付  2025-06-04
10   5808071569   食品    矿泉水     9   29     重庆   支付宝  2025-06-04
13   6880065056   图书    练习册     8   39     深圳   支付宝  2025-06-04
16   5812573980   食品     坚果     2   79     南京  微信支付  2025-06-05
26   5854211330   食品     果干     9   59     长沙   支付宝  2025-06-07
38   6896363474   图书    练习册     7   39     成都   支付宝  2025-06-09
39   6857955578   图书    科普书     5   59     武汉  微信支付  2025-06-10
42   5848602769   食品    能量棒     1   49     福州  微信支付  2025-06-12
43   6896687125   食品     果汁     2   39     合肥   支付宝  2025-06-12
48   5835099410   图书   技术书籍     4   89     福州  微信支付  2025-06-14
49   6842655345   食品     蜂蜜     7   89     天津   支付宝  2025-06-14
55   6840254213   食品    矿泉水    10   29     天津  微信支付  2025-06-15
59   5805524413   食品     牛奶     5   69     上海   支付宝  2025-06-16
61   5876009437   食品     肉脯     7   69     北京  微信支付  2025-06-17
70   5857892499   食品    巧克力     6   59     合肥  微信支付  2025-06-19
72   6882472708   食品  零食大礼包     5   89     福州  微信支付  2025-06-19
82   5882040279   图书    练习册     3   39     青岛  微信支付  2025-06-22
87   5824138220   图书     日历     3   39     青岛   支付宝  2025-06-23
96   6882159173   食品     蜂蜜     7   89     武汉  微信支付  2025-06-27
97   6847661479   食品     薯片     8   19     重庆   支付宝  2025-06-27
98   5848428039   食品     茶叶    10  199     重庆  微信支付  2025-06-27
99   6868231493   食品     薯片     5   19     南京  微信支付  2025-06-27
101  6899145716   图书     杂志     8   29     合肥   支付宝  2025-06-29
104  6827358966   图书     字典     6   99     郑州   支付宝  2025-06-29
111  5838735887   图书     画册     7   99     天津   支付宝  2025-07-01
113  5818261249   食品     茶叶     6  199     郑州   支付宝  2025-07-02
116  5854511595   食品  零食大礼包     2   89     武汉   支付宝  2025-07-03
118  6865301539   食品  零食大礼包     4   89     长沙   支付宝  2025-07-03
121  6892321515   食品     坚果    10   79     西安  微信支付  2025-07-04
122  5883797573   食品     麦片     7   49     成都  微信支付  2025-07-04
125  6818053882   食品     牛奶     4   69     广州   支付宝  2025-07-05
128  5866054840   图书     字典    10   99     南京   支付宝  2025-07-06
130  5839652877   图书     漫画     5   39     厦门   支付宝  2025-07-06
137  5813233987   食品    方便面     5   49     昆明  微信支付  2025-07-07
140  5831376701   食品     薯片     2   19     武汉  微信支付  2025-07-08
141  5879174422   图书    散文集     6   59     苏州  微信支付  2025-07-09
144  6832294234   食品     咖啡     2  129     上海  微信支付  2025-07-09
151  5893341133   食品     糖果     7   39     福州  微信支付  2025-07-13
152  6875304597   食品    能量棒     8   49     杭州  微信支付  2025-07-13
156  6811607405   食品     饼干     6   39     青岛   支付宝  2025-07-14
157  6869448173   食品    巧克力     3   59     天津  微信支付  2025-07-15
158  5848997046   图书    散文集     8   59     天津  微信支付  2025-07-15
160  6821795644   食品     咖啡     8  129     长沙   支付宝  2025-07-15
162  6855377041   图书     日历     5   39     西安   支付宝  2025-07-16
171  5879241383   图书    摄影集     5  129     杭州   支付宝  2025-07-19
172  6890353450   食品    方便面     5   49     南京   支付宝  2025-07-19
186  5837602170   图书     字帖     8   29     天津   支付宝  2025-07-24
188  5816285494   食品     牛奶     1   69     郑州   支付宝  2025-07-25
193  6859826757   图书     画册     2   99     宁波   支付宝  2025-07-25
194  6855967378   图书     字帖     6   29     昆明   支付宝  2025-07-26
198  5823039491   图书    练习册     2   39     重庆  微信支付  2025-07-27
199  6844981163   食品     茶叶     2  199     深圳   支付宝  2025-07-27
208  5822667696   图书    摄影集     8  129     上海   支付宝  2025-07-31
210  5868514156   食品     果干    10   59     广州   支付宝  2025-07-31
218  6879211098   图书    练习册    10   39     深圳  微信支付  2025-08-03
220  5853054830   食品     肉脯     1   69     北京  微信支付  2025-08-04
224  5891062479   食品     饼干    10   39     宁波   支付宝  2025-08-04
232  5827118463   食品     面包    10   29     重庆   支付宝  2025-08-07
240  5876354209   图书    笔记本     5   49     福州   支付宝  2025-08-11
241  6804390223   食品     糖果     6   39     合肥  微信支付  2025-08-11
244  5893361218   图书    笔记本     3   49     南京  微信支付  2025-08-12
247  6889194588   食品    巧克力     5   59     天津   支付宝  2025-08-12
249  6882063897   食品    巧克力     4   59     重庆  微信支付  2025-08-13
251  6815487266   图书   技术书籍     5   89     广州   支付宝  2025-08-14
255  6874166656   食品     麦片     2   49     南京   支付宝  2025-08-15
256  6888548139   食品    能量棒     7   49     杭州   支付宝  2025-08-16
259  6890392173   食品     茶叶     5  199     武汉   支付宝  2025-08-16
265  5823329114   图书     字典     7   99     天津  微信支付  2025-08-18
275  5836984659   图书     食谱     7   49     天津  微信支付  2025-08-20
277  6890876412   食品     海苔     1   29     武汉  微信支付  2025-08-21
278  6824270558   食品     薯片     1   19     武汉   支付宝  2025-08-22
283  5865254576   食品    方便面     2   49     长沙   支付宝  2025-08-23
288  6820986832   食品     肉脯     3   69     广州   支付宝  2025-08-24
292  5877457110   食品     蜂蜜     2   89     重庆   支付宝  2025-08-25
293  5832560118   食品     薯片     7   19     北京   支付宝  2025-08-25
299  6889261873   图书    笔记本     8   49     南京  微信支付  2025-08-27
300  6869253277   食品    方便面     1   49     北京   支付宝  2025-08-27
302  6869886459   图书     教材     3   79     厦门   支付宝  2025-08-28
303  6806160339   食品  零食大礼包     3   89     青岛   支付宝  2025-08-29
304  6862175114   食品     面包     8   29     成都   支付宝  2025-08-29
305  6827231926   图书     字典     4   99     长沙  微信支付  2025-08-29
307  6807847191   图书     漫画     8   39     杭州   支付宝  2025-08-29
311  5855677494   食品     坚果    10   79     宁波   支付宝  2025-08-30
313  6833144246   食品    能量棒     5   49     厦门   支付宝  2025-08-31
314  6889158121   食品     牛奶    10   69     厦门  微信支付  2025-08-31
315  5881823286   图书     画册     5   99     长沙  微信支付  2025-08-31
316  6801495528   图书    历史书     9   89     福州  微信支付  2025-09-01
320  5830696359   食品     坚果     3   79     上海   支付宝  2025-09-01
325  6809660384   食品    矿泉水     5   29     北京  微信支付  2025-09-03
327  5876386922   图书     漫画     6   39     昆明   支付宝  2025-09-03
329  6862898039   图书     字帖     9   29     南京   支付宝  2025-09-04
332  6836140342   食品  零食大礼包     1   89     郑州  微信支付  2025-09-06
333  6866915478   图书     绘本     2   59     北京  微信支付  2025-09-06
334  5872942373   食品     饼干     8   39     厦门  微信支付  2025-09-06
335  6851028631   图书     字帖     1   29     成都   支付宝  2025-09-06
339  6840926430   图书    摄影集    10  129     杭州  微信支付  2025-09-08
340  5834735575   食品     酸奶     5   59     成都   支付宝  2025-09-08
342  6851411201   图书     字典     3   99     宁波   支付宝  2025-09-09
351  5878252086   食品     肉脯     7   69     郑州   支付宝  2025-09-11
356  6890163345   食品    矿泉水     9   29     南京   支付宝  2025-09-13
357  5866711381   食品     肉脯    10   69     成都   支付宝  2025-09-13
360  6862143082   图书    散文集    10   59     武汉   支付宝  2025-09-14
379  5852580673   食品     坚果     1   79     深圳   支付宝  2025-09-20
382  5844830398   食品     茶叶     9  199     郑州  微信支付  2025-09-21
386  6835453724   图书    科普书     3   59     青岛   支付宝  2025-09-23
388  6873163407   图书    摄影集     7  129     青岛   支付宝  2025-09-24
392  6802890262   图书     小说     9   49     天津  微信支付  2025-09-26
394  5868828994   图书     字典     7   99     苏州  微信支付  2025-09-26
399  6860434598   图书     诗集     3   49     福州   支付宝  2025-09-28
402  6886426092   图书   技术书籍     7   89     合肥  微信支付  2025-09-30
411  5833331680   食品     果汁     5   39     杭州  微信支付  2025-10-03
421  6822571575   食品    方便面    10   49     青岛   支付宝  2025-10-05
424  6872487503   食品     糖果     7   39     南京   支付宝  2025-10-05
428  6898670721   图书     教材     9   79     西安   支付宝  2025-10-06
430  6806527815   图书     漫画     7   39     天津  微信支付  2025-10-07
434  5840421293   食品     茶叶    10  199     郑州   支付宝  2025-10-08
436  5802528062   图书     字帖     3   29     厦门   支付宝  2025-10-08
437  6876227672   食品    方便面    10   49     天津   支付宝  2025-10-08
440  6841526591   图书     绘本     2   59     福州   支付宝  2025-10-12
450  5892891438   食品     麦片     5   49     天津   支付宝  2025-10-14
451  6857291518   图书     小说     4   49     合肥  微信支付  2025-10-14
463  5882153266   图书   旅游指南     4   69     南京   支付宝  2025-10-18
464  6800227885   食品     蜂蜜     4   89     杭州  微信支付  2025-10-18
474  6897454715   食品     面包     5   29     重庆   支付宝  2025-10-20
476  5815751088   图书    历史书     5   89     宁波  微信支付  2025-10-21
478  5861615084   食品     海苔     7   29     宁波   支付宝  2025-10-21
479  6887791768   食品  零食大礼包     7   89     重庆  微信支付  2025-10-22
480  5886204084   图书     杂志    10   29     成都   支付宝  2025-10-22
486  6887669254   食品     果汁     9   39     天津   支付宝  2025-10-25
487  6866905032   图书    散文集     2   59     昆明  微信支付  2025-10-26
493  6854016886   图书     字典     7   99     天津   支付宝  2025-10-28
495  5801866775   图书     杂志    10   29     西安   支付宝  2025-10-28
499  5894965586   图书     字典     6   99     上海  微信支付  2025-10-29
502  6891182351   食品     麦片     6   49     宁波   支付宝  2025-10-30
504  5828097577   图书     诗集     5   49     天津  微信支付  2025-10-31
507  6806891687   图书     杂志    10   29     宁波   支付宝  2025-11-01
511  5864988754   图书    练习册     6   39     西安   支付宝  2025-11-02
512  5849276226   图书    散文集    10   59     成都   支付宝  2025-11-02
513  6892560636   图书   技术书籍     9   89     广州   支付宝  2025-11-03
514  5807367507   食品     酸奶     2   59     上海   支付宝  2025-11-03
516  5870995622   食品     果汁     3   39     广州   支付宝  2025-11-03
521  5827669048   食品     麦片     6   49     南京   支付宝  2025-11-04
533  5801461172   食品     海苔     2   29     青岛   支付宝  2025-11-07
534  5888544474   食品     糖果     3   39     广州  微信支付  2025-11-07
537  5822076434   图书     字帖     8   29     杭州  微信支付  2025-11-08
538  6846010084   图书     教材     8   79     福州  微信支付  2025-11-08
540  5828868579   图书     教材     5   79     南京  微信支付  2025-11-08
545  6859510952   食品     酸奶     1   59     福州   支付宝  2025-11-12
546  6843273729   食品     果汁     1   39     成都  微信支付  2025-11-12
548  6856749011   图书    摄影集     9  129     武汉  微信支付  2025-11-12
555  6814348900   食品     牛奶     2   69     杭州   支付宝  2025-11-14
556  6835195484   食品     坚果     1   79     郑州   支付宝  2025-11-14
561  5844858451   图书     杂志     7   29     郑州  微信支付  2025-11-15
562  6890733017   食品     蜂蜜     5   89     重庆   支付宝  2025-11-16
564  6873098065   图书     字典     4   99     南京  微信支付  2025-11-17
572  6878127702   图书     杂志     9   29     杭州   支付宝  2025-11-18
578  6869496866   图书    散文集     7   59     杭州  微信支付  2025-11-20
580  6818144493   图书     教材     6   79     宁波  微信支付  2025-11-20
585  6840013941   食品     薯片    10   19     青岛  微信支付  2025-11-23
587  6805424379   食品     蜂蜜     2   89     昆明   支付宝  2025-11-24
588  5862509425   图书     字帖     8   29     福州   支付宝  2025-11-24
601  6838249011   食品     牛奶     5   69     郑州  微信支付  2025-11-27
602  5878898156   图书    历史书     4   89     深圳  微信支付  2025-11-27
603  6888122019   食品     薯片     9   19     重庆   支付宝  2025-11-28
606  6811426830   食品     果干     9   59     苏州  微信支付  2025-11-28
608  5826023717   食品    方便面    10   49     合肥  微信支付  2025-11-29
615  5801601835   食品     坚果     4   79     杭州   支付宝  2025-11-30
617  5805561986   食品     麦片     7   49     郑州  微信支付  2025-12-01
619  6814787700   食品     酸奶     2   59     南京   支付宝  2025-12-01
622  6826401287   食品     果汁     1   39     福州   支付宝  2025-12-02
627  6876391705   图书    散文集     4   59     郑州   支付宝  2025-12-05
629  6881159219   食品  零食大礼包     9   89     青岛   支付宝  2025-12-05
630  6838456073   食品    能量棒     3   49     西安   支付宝  2025-12-05
632  6852775012   图书     杂志     4   29     昆明   支付宝  2025-12-05
641  6854598751   图书     画册     6   99     苏州   支付宝  2025-12-08
643  6882465065   食品     咖啡     8  129     杭州   支付宝  2025-12-09
646  6886473200   图书    历史书     9   89     北京   支付宝  2025-12-09
647  6800132162   食品    巧克力     7   59     南京   支付宝  2025-12-09
648  6836203669   图书     日历     9   39     深圳   支付宝  2025-12-10
654  6824531780   食品     酸奶     2   59     武汉   支付宝  2025-12-11
655  5858811924   图书     日历     5   39     厦门   支付宝  2025-12-11
659  5820099845   食品     面包     8   29     青岛  微信支付  2025-12-13
660  5894543795   食品     蜂蜜     2   89     深圳  微信支付  2025-12-13
664  6890554963   食品     果汁     9   39     南京  微信支付  2025-12-14
665  5838827496   食品    矿泉水     8   29     昆明   支付宝  2025-12-15
678  6858202357   食品     海苔     1   29     苏州   支付宝  2025-12-17
688  6833307089   图书     小说    10   49     成都  微信支付  2025-12-20
690  5889119247   食品     酸奶     7   59     广州   支付宝  2025-12-21
693  5884386495   图书    摄影集     3  129     天津   支付宝  2025-12-22
694  6893767116   食品     肉脯     5   69     长沙   支付宝  2025-12-22
697  5846696675   食品     海苔     6   29     武汉  微信支付  2025-12-23
698  6867806084   图书    练习册     8   39     西安  微信支付  2025-12-25
705  6841206026   图书     小说     4   49     广州   支付宝  2025-12-27
714  5869332601   图书     食谱     4   49     杭州   支付宝  2025-12-29
717  6863194415   食品    巧克力     2   59     广州  微信支付  2025-12-29
726  5878068551   食品     蜂蜜     1   89     长沙   支付宝  2026-01-01
728  6887007128   食品    方便面     3   49     郑州   支付宝  2026-01-01
732  6882409558   图书     字帖     7   29     长沙  微信支付  2026-01-02
733  6846834565   食品     蜂蜜     8   89     厦门   支付宝  2026-01-02
737  5896329735   食品     牛奶     7   69     郑州  微信支付  2026-01-03
740  5800978577   食品     肉脯     1   69     杭州   支付宝  2026-01-03
742  6804979734   图书     漫画    10   39     重庆  微信支付  2026-01-03
743  6808516843   食品     糖果     8   39     郑州   支付宝  2026-01-04
746  6873188858   食品     面包     2   29     上海  微信支付  2026-01-05
753  6850321380   食品    方便面     1   49     长沙   支付宝  2026-01-08
757  6894941319   食品     牛奶     2   69     深圳   支付宝  2026-01-09
762  5817045287   图书     绘本     4   59     上海   支付宝  2026-01-11
763  5835191671   图书     小说     8   49     成都  微信支付  2026-01-12
764  6857397864   食品     酸奶     3   59     昆明   支付宝  2026-01-12
766  6881818665   食品     坚果     8   79     南京   支付宝  2026-01-12
769  6834624594   图书   技术书籍     7   89     北京   支付宝  2026-01-13
770  6813932695   图书     绘本     3   59     合肥  微信支付  2026-01-13
777  6819383488   食品     咖啡     8  129     杭州   支付宝  2026-01-15
779  6866812257   图书   旅游指南     7   69     深圳   支付宝  2026-01-15
783  5844235853   图书   技术书籍     4   89     北京  微信支付  2026-01-17
784  6851230423   图书    散文集     9   59     厦门  微信支付  2026-01-17
792  6801790157   图书     漫画     5   39     福州  微信支付  2026-01-20
794  5880271871   食品     薯片     4   19     厦门   支付宝  2026-01-21
795  5818218201   图书     绘本    10   59     南京  微信支付  2026-01-21
797  5829660564   图书     小说     3   49     重庆  微信支付  2026-01-21
798  5896831836   食品     蜂蜜     4   89     长沙   支付宝  2026-01-22
809  5822289941   图书     画册     1   99     昆明  微信支付  2026-01-25
811  5806281144   图书     画册     3   99     南京   支付宝  2026-01-25
812  5804522125   食品     茶叶     4  199     合肥  微信支付  2026-01-25
814  6862831115   图书    摄影集     1  129     广州   支付宝  2026-01-25
815  6827507349   食品    方便面     1   49     厦门   支付宝  2026-01-25
822  6860643473   图书     小说     9   49     昆明   支付宝  2026-01-27
825  5844362711   食品  零食大礼包     9   89     宁波  微信支付  2026-01-28
827  5886930931   食品     饼干     3   39     昆明   支付宝  2026-01-29
844  6891557148   图书   旅游指南     3   69     上海  微信支付  2026-02-03
851  5830886559   图书    科普书     4   59     郑州   支付宝  2026-02-05
858  5869018230   食品     果汁     5   39     青岛   支付宝  2026-02-07
864  5848247967   图书     绘本     9   59     郑州   支付宝  2026-02-09
867  6816657166   图书     教材    10   79     郑州  微信支付  2026-02-09
869  6805587795   食品     咖啡     5  129     广州   支付宝  2026-02-10
870  6832841492   图书     诗集     6   49     西安   支付宝  2026-02-11
872  5827187927   食品     坚果     2   79     北京  微信支付  2026-02-12
877  6819364658   食品    能量棒     1   49     西安   支付宝  2026-02-13
878  5897559004   图书    历史书     2   89     天津   支付宝  2026-02-13
880  5808511315   图书     食谱     7   49     天津   支付宝  2026-02-14
883  6816373891   图书     字典     2   99     昆明  微信支付  2026-02-16
886  5845686917   食品    矿泉水    10   29     厦门   支付宝  2026-02-16
897  6838816181   食品     海苔     3   29     福州  微信支付  2026-02-19
903  5862381963   食品    巧克力     2   59     郑州   支付宝  2026-02-22
906  5815953258   食品     蜂蜜     1   89     苏州   支付宝  2026-02-23
907  5890411651   食品     茶叶     8  199     上海  微信支付  2026-02-23
910  5823746636   食品    矿泉水     1   29     西安   支付宝  2026-02-24
911  5813388774   食品     饼干     8   39     宁波   支付宝  2026-02-24
915  6828928851   食品    矿泉水     9   29     福州  微信支付  2026-02-25
921  6859580477   食品     果汁    10   39     南京  微信支付  2026-02-26
924  6890368843   食品     牛奶     9   69     成都   支付宝  2026-02-28
928  5898559914   图书     画册     7   99     杭州   支付宝  2026-03-01
929  6844507218   图书     杂志     1   29     宁波   支付宝  2026-03-01
930  5865877696   食品     牛奶    10   69     重庆  微信支付  2026-03-01
931  5842520913   图书     杂志     6   29     重庆   支付宝  2026-03-01
932  5837665363   食品     茶叶     2  199     宁波  微信支付  2026-03-01
940  6827649901   食品     牛奶     3   69     上海  微信支付  2026-03-05
943  5835405260   食品     饼干     4   39     天津  微信支付  2026-03-06
945  5801611195   图书     漫画     6   39     昆明  微信支付  2026-03-06
950  6840652306   食品     牛奶     2   69     北京  微信支付  2026-03-08
952  5877681820   食品    巧克力     9   59     南京   支付宝  2026-03-08
955  6875099532   食品     果汁     1   39     武汉   支付宝  2026-03-09
965  6814840827   图书    练习册    10   39     昆明  微信支付  2026-03-12
966  5841243581   图书    历史书     2   89     天津   支付宝  2026-03-12
967  6848472509   食品     酸奶     1   59     杭州   支付宝  2026-03-12
972  5867305556   食品     肉脯     3   69     重庆  微信支付  2026-03-13
973  6836237383   图书     教材     8   79     天津  微信支付  2026-03-13
976  6835452753   食品     牛奶     2   69     青岛   支付宝  2026-03-14
977  5863520484   图书     教材     7   79     深圳   支付宝  2026-03-14
978  5855860680   食品     蜂蜜     7   89     郑州  微信支付  2026-03-14
980  5825695022   图书    科普书     9   59     长沙   支付宝  2026-03-15
989  6879395963   图书    散文集     4   59     长沙   支付宝  2026-03-18
995  5887473055   图书     小说    10   49     长沙  微信支付  2026-03-20
996  5808511756   食品     坚果     2   79     成都   支付宝  2026-03-20
998  6876456690   食品     果汁     7   39     广州   支付宝  2026-03-20